salt_2015.8.%.bbappend: add missing getVar() argument
Post-Jethro releases have made specyfing the last arg of getVar()
mandatory. If it is missing, a build error will be triggered:

Exception: TypeError: getVar() takes at least 3 arguments (2 given)
ERROR: Failed to parse recipe: /media/adi/ssd/nilrt-master/build/../sources/meta-cloud-services/meta-openstack/recipes-support/salt/salt_2015.8.0.bb

Of course this still works in Jethro, but better fix it now than later.

Signed-off-by: Ioan-Adrian Ratiu <adrian.ratiu@ni.com>