xfce-nilrt-settings: add missing bash rdepends
To avoid the following error:
ERROR: xfce-nilrt-settings-1.0-r0 do_package_qa: QA Issue:
/usr/local/natinst/bin/dual-monitor-setup.sh contained in package
xfce-nilrt-settings requires /bin/bash, but no providers found in
RDEPENDS_xfce-nilrt-settings? [file-rdeps]

Signed-off-by: Ioan-Adrian Ratiu <adrian.ratiu@ni.com>