packagegroup-ni-ptest: create packagegroup
This packagegroup contains all NI-added ptests. It is needed because
we can't simply add these packages to the minimal-nilrt-ptest-image
because we break dependencies using IMAGE_INSTALL_NODEPS and every
image containing packages directly will fail with errors like:

ERROR: Unable to install packages. Command '/media/adi/ssd/nilrt-jethro/build/tmp-glibc/sysroots/x86_64-linux/usr/bin/opkg --volatile-cache -f /media/adi/ssd/nilrt-jethro/build/tmp-glibc/work/x64-nilrt-linux/minimal-nilrt-ptest-image/1.0-r0/opkg.conf -o /media/adi/ssd/nilrt-jethro/build/tmp-glibc/work/x64-nilrt-linux/minimal-nilrt-ptest-image/1.0-r0/rootfs --force_postinstall --prefer-arch-to-version   install niminionagent nirtcfg ptest-runner glibc-tests-ptest opkg rt-tests packagegroup-ni-base salt-tests packagegroup-ni-tzdata python-salttesting kernel-tests-ptest salt-ptest' returned 255:
Collected errors:
 * opkg_prepare_url_for_install: Couldn't find anything to satisfy 'glibc-tests-ptest'.

The only way to fix this is to keep running package-index after builds
fail or add these packages to a packagegroup and bitbake the pkggroup
so the do_rootfs task can pick up them up without failing.

This implements the second solution i.e. moves all packages to a group.

Reviewed-by: Ken Sharp <ken.sharp@ni.com>
Reviewed-by: Alejandro del Castillo <adejandro.del.castillo@ni.com>
Signed-off-by: Ioan-Adrian Ratiu <adrian.ratiu@ni.com>