fixup! linux-nilrt: Add machine-specific defconfig, dtbs, gcc opts
The commit changed the way we append to EXTRA_OEMAKE and this causes
build failures because the new _append syntax does not add whitespace
when appending so we end up with the following call in run.do_compile
(taken from the devshell):

make -j 8  HOSTCC="gcc " HOSTCPP="gcc  -E"CFLAGS=" --sysroot=..."

This triggers the following error because CFLAGS is ignored:

(...)/build/tmp-glibc/work-shared/x64/kernel-source/scripts/recordmcount.c:24:23:
fatal error: sys/types.h: No such file or directory
|  #include <sys/types.h>

Signed-off-by: Ioan-Adrian Ratiu <adrian.ratiu@ni.com>