logrotate: remove duplicate lines
I messed up during the meta-nilrt merge and forgot to remove some
duplicated lines which triggered this error when running logrotate:

$ logrotate /etc/logrotate.conf
error: /etc/logrotate.conf:40 duplicate log entry for /var/log/messages

Signed-off-by: Ioan-Adrian Ratiu <adrian.ratiu@ni.com>